// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Ofi9k1qeiXfvTKxGvrL0AZm_kntoQc0',
    appId: '1:754431644910:web:592f8e346047f963168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    authDomain: 'quickdoodle-e386e.firebaseapp.com',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    measurementId: 'G-JHT7SSN9D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWe3L59UQOE55TmgbJUStsUdBpNYToC0',
    appId: '1:754431644910:android:7eff4f8b10c1a43b168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxGmzOsV8xJHupNYfnvtbCGC-rH9k1GvY',
    appId: '1:754431644910:ios:c470ff4a0a8afbf3168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    iosBundleId: 'com.example.quickDoodle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxGmzOsV8xJHupNYfnvtbCGC-rH9k1GvY',
    appId: '1:754431644910:ios:c470ff4a0a8afbf3168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    iosBundleId: 'com.example.quickDoodle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Ofi9k1qeiXfvTKxGvrL0AZm_kntoQc0',
    appId: '1:754431644910:web:3c282ef54e08efa8168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    authDomain: 'quickdoodle-e386e.firebaseapp.com',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    measurementId: 'G-PYVSHEVRTL',
  );
}
